### your site title here

title: Gean Ramos - U1M.com.br
baseurl: /hagura # name of the repository
email: geancr10@gmail.com



highlighter: rouge
markdown: kramdown


paginate: 4


# Tracker
analytics: UA-59300081-1

# Comments
disqus-shortname: geanramos


#optimization
#compress.html
compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: true
  profile: true
  startings: []


sass:
 style: compressed

exclude:
- README.md


plugins:
  - jekyll-seo-tag
  - jekyll-paginate
